[package]
name = "chatty-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
relm4 = { version = "0.9.1", features = ["libadwaita"] }
relm4-components = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
